name: Continous Integration

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: frontend tests
        run: |
          cd frontend
          npm ci
          npm run test

      - name: backend tests
        run: |
          cd backend
          npm ci
          npm run test
