name: E2E Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start Docker Containers
        run: docker-compose -f docker-compose.yml up -d
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_URL: ${{ secrets.API_URL }}
        timeout-minutes: 5

      - name: Install dependencies
        run: |
          cd e2e
          npm ci

      - name: Install Playwright Browsers
        run: |
          cd e2e
          npx playwright install --with-deps

      - name: Test API Connectivity
        run: curl -I https://api.binance.com/api/v3/ticker/price

      - name: Wait for Services
        run: |
          until $(curl --output /dev/null --silent --head --fail http://localhost:5001); do
            printf '.'
            sleep 5
          done
        timeout-minutes: 5

       - name: Wait for Services
        run: |
          until $(curl --output /dev/null --silent --head --fail http://localhost:5173); do
            printf '.'
            sleep 5
          done
        timeout-minutes: 5

      - name: Run Playwright tests
        run: |
          cd e2e
          npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: e2e/playwright-report/
          retention-days: 30

      - name: Show Docker Logs
        run: docker-compose -f docker-compose.yml logs

      - name: Stop Docker Containers
        if: always()
        run: docker-compose -f docker-compose.yml down
